name: Deploy to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Navega al directorio del proyecto
            cd /var/www/html
            
            # Asegura de que el repositorio esté configurado correctamente
            if [ ! -d ".git" ]; then
              echo "Initializing Git repository in /var/www/html"
              git init
              git remote add origin https://github.com/AndyChiquin/My-Static-Page-.git
              git fetch origin main
              git reset --hard origin/main
            fi
            
            # Actualiza el código desde la rama principal
            git pull origin main || { echo "Git pull failed"; exit 1; }
            
            # Reinicia Apache para aplicar los cambios
            sudo systemctl restart apache2 || { echo "Failed to restart Apache"; exit 1; }
          EOF
