name: Deploy to EC2

on:
  push:
    branches:
      - main  # Puedes cambiar 'main' por la rama que prefieras para hacer el despliegue

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /var/www/html
            git pull origin main  # Cambia 'main' por tu rama si es diferente
            sudo systemctl restart apache2
          EOF
